[package]
name = "gol-burn"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17.0", features = ["cuda", "std"] }
clap = { version = "4.5.38", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1